### ISSUE TITLE
may you rename curcuna here:

### ISSUE THREAD

**Issue by georgid** [MTG/turkish_makam_audio_score_alignment_dataset#1]
rename this dir 
https://github.com/MTG/turkish_makam_audio_score_alignment_dataset/tree/master/data/nihavent--sarki--curcuna--kimseye_etmem--kemani_sarkis_efendi

to 

https://github.com/MTG/turkish_makam_audio_score_alignment_dataset/tree/master/data/nihavent--sarki--kapali_curcuna--kimseye_etmem--kemani_sarkis_efendi

because I have symbTr name automatically fetched from dunya and it says kapali_curcuna

**Comment by sertansenturk** [comment]
Done!
